### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jbelien** [oSoc20/urban-brussels-api#11]

**Comment by AnastasiaDv491** [comment]
Waiting for the back-end to implement the search function to connect to the search bar at the front-end

**Comment by jbelien** [comment]
@AnastasiaDv491 Please give some more details about what you're expecting from the API ! What does the front-end need ?

**Comment by AnastasiaDv491** [comment]
the front-end needs to connect the search engine to the api so it renders data based on the name/address of the building
